name: suprise
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.1
  audioplayers: ^0.19.1
  confetti: ^0.6.0-nullsafety
  cupertino_icons: ^1.0.3
  flutter_icons:
    git:
      url: git://github.com/jibiel/flutter-icons.git
      ref: master
  get: ^4.3.8
  lottie: ^1.1.0
  simple_animations: ^3.1.1
  url_launcher: ^6.0.9
  url_strategy: null

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.1
  flutter_gen_runner: ^3.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/lottie/
    - assets/illustrations/
  fonts:
    - family: Canterbury
      fonts:
        - asset: assets/fonts/Canterbury.ttf
    - family: Bebas-Regular
      fonts:
        - asset: assets/fonts/Bebas-Regular.otf
    - family: SourceSansPro-Italic
      fonts:
        - asset: assets/fonts/SourceSansPro-Italic.ttf
    - family: SourceSansPro-Regular
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf
